// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been defined for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:android:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    storageBucket: 'cipher-7791c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:ios:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    storageBucket: 'cipher-7791c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:macos:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    storageBucket: 'cipher-7791c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:web:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    authDomain: 'cipher-7791c.firebaseapp.com',
    databaseURL: 'https://cipher-7791c-default-rtdb.firebaseio.com',
    storageBucket: 'cipher-7791c.firebasestorage.app',
    measurementId: 'G-YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:linux:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    storageBucket: 'cipher-7791c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPWdZ8dgaC5HjcGapRoMJwOxBmmz50d-4',
    appId: '1:720039098644:windows:c6ffce28a65aedb546ea01',
    messagingSenderId: '720039098644',
    projectId: 'cipher-7791c',
    storageBucket: 'cipher-7791c.appspot.com',
  );
}